### ISSUE TITLE
Parsing LookupWithKey packets

### ISSUE THREAD

**Issue by yooo1999** [pmarrapese/iot#2]
Please parse the `message_type == 0x26`
As you can see [here](https://github.com/bropat/eufy-security-client/blob/master/src/p2p/utils.ts#L59) that message is for P2P connection with DSK key

**Comment by pmarrapese** [comment]
Added `MSG_P2P_REQ_DSK` (0x26) and a few other V4 messages in fab6ac98ed729c6496ea35d4c8c3f1eedf299d53 :)
